import { jsPDF } from 'jspdf';
import { SurplusItem, User } from './store';
import { toast } from 'sonner';

export const generateFoodReport = (item: SurplusItem, allUsers: User[]) => {
  try {
    const doc = new jsPDF();
    const ngoUser = allUsers.find(u => u.id === item.requestedBy);
    
    // Metrics
    const meals = item.quantity * 2;
    const co2 = item.quantity * 2.5;
    const waste = item.quantity;

    // Header
    doc.setFillColor(34, 197, 94); // Primary green
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Food Redistribution Report', 20, 25);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('A Food Loop Impact Certificate', 20, 32);

    // Section 1: Pickup Details
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('1. Pickup Details', 20, 55);
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 57, 190, 57);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Pickup ID: ${item.id}`, 25, 65);
    doc.text(`Completed Date: ${item.completedAt ? new Date(item.completedAt).toLocaleString() : 'N/A'}`, 25, 72);
    doc.text(`Status: COMPLETED`, 25, 79);

    // Section 2: Canteen Details
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('2. Canteen Details', 20, 92);
    doc.line(20, 94, 190, 94);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Source Canteen: ${item.canteenName}`, 25, 102);

    // Section 3: NGO Details
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('3. NGO Details', 20, 115);
    doc.line(20, 117, 190, 117);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Recipient NGO: ${item.requestedByName || ngoUser?.organization || 'Registered NGO'}`, 25, 125);
    
    let nextY = 132;
    if (ngoUser?.reg_no) {
      doc.text(`Registration No: ${ngoUser.reg_no}`, 25, nextY);
      nextY += 7;
    }
    if (ngoUser?.location || ngoUser?.address) {
      doc.text(`NGO Location: ${ngoUser.location || ngoUser.address}`, 25, nextY);
      nextY += 7;
    }

    // Section 4: Food Details
    const section4Y = Math.max(148, nextY + 10);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('4. Food Details', 20, section4Y - 10);
    doc.line(20, section4Y - 8, 190, section4Y - 8);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Food Item: ${item.food}`, 25, section4Y);
    doc.text(`Quantity: ${item.quantity} kg`, 25, section4Y + 7);
    doc.text(`Pickup Location: ${item.location}`, 25, section4Y + 14);

    // Section 5: Impact Metrics
    const section5Y = section4Y + 28;
    doc.setFillColor(240, 253, 244); // Very light green
    doc.roundedRect(20, section5Y, 170, 45, 3, 3, 'F');
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(22, 163, 74); // Darker green
    doc.text('5. Environmental & Social Impact', 25, section5Y + 10);
    
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(`• Meals Served: ${meals} meals provided to community`, 30, section5Y + 20);
    doc.text(`• CO2 Saved: ${co2.toFixed(1)} kg emissions prevented`, 30, section5Y + 27);
    doc.text(`• Waste Reduced: ${waste} kg food diverted from landfills`, 30, section5Y + 34);

    // Certification
    const footerStartY = section5Y + 58;
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.text('"This redistribution helped reduce food waste and support community needs."', 20, footerStartY);
    
    // Badge
    doc.setFillColor(22, 163, 74);
    doc.rect(140, footerStartY + 10, 50, 12, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Eco Impact Verified', 145, footerStartY + 18);

    // Footer
    doc.setTextColor(150, 150, 150);
    doc.setFontSize(8);
    doc.text(`Generated by Food Loop Dashboard on ${new Date().toLocaleString()}`, 20, 280);

    doc.save(`Food_Report_${item.id}.pdf`);
    toast.success("PDF Report downloaded successfully!");
  } catch (err) {
    console.error(err);
    toast.error("Failed to generate PDF");
  }
};

export const generateSafeCertificate = (
  image: string, 
  results: any, 
  canteenName: string
) => {
  try {
    const doc = new jsPDF();
    const certId = `CERT-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;

    // Header with Emerald Gradient Style
    doc.setFillColor(16, 185, 129); // Emerald-500
    doc.rect(0, 0, 210, 45, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(26);
    doc.setFont('helvetica', 'bold');
    doc.text('FOOD SAFETY CERTIFICATE', 105, 25, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Verified by Food Loop Smart AI Diagnostics', 105, 33, { align: 'center' });

    // Certificate ID & Timestamp
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(9);
    doc.text(`Certificate ID: ${certId}`, 20, 55);
    doc.text(`Generated On: ${new Date().toLocaleString()}`, 140, 55);

    // Section 1: Food Evidence (The Photo)
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('1. Visual Evidence Scan', 20, 68);
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 70, 190, 70);

    // Embed Image (Base64)
    try {
      // Position the image in the center
      doc.addImage(image, 'JPEG', 35, 75, 140, 90);
      doc.setDrawColor(16, 185, 129);
      doc.rect(34, 74, 142, 92); // Border for image
    } catch (e) {
      doc.text('[Image Data Error: Could not render binary stream]', 50, 120);
    }

    // Section 2: AI Diagnostic Results
    const sec2Y = 180;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('2. AI Diagnostic Results', 20, sec2Y);
    doc.line(20, sec2Y + 2, 190, sec2Y + 2);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`• Freshness Index: ${results.freshness}%`, 25, sec2Y + 12);
    doc.text(`• Color Saturation: ${results.color}%`, 25, sec2Y + 20);
    doc.text(`• Texture Score: ${results.texture}%`, 25, sec2Y + 28);
    
    doc.text(`• Ambient Temperature: ${results.temp}°C`, 120, sec2Y + 12);
    doc.text(`• Humidity Level: ${results.humidity}%`, 120, sec2Y + 20);
    doc.text(`• Prediction Model: FoodLoop-v4.2-ML`, 120, sec2Y + 28);

    // Safety Verdict Box
    const verdictY = 220;
    doc.setFillColor(236, 253, 245); // Light emerald
    doc.setDrawColor(16, 185, 129);
    doc.roundedRect(20, verdictY, 170, 35, 3, 3, 'FD');

    doc.setTextColor(5, 150, 105); // Emerald-600
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('VERDICT: SAFE TO DISTRIBUTE', 105, verdictY + 15, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Estimated Expiry: Within ${results.expiryHours}h ${results.expiryMinutes}m`, 105, verdictY + 25, { align: 'center' });

    // Official Seal (Watermark effect)
    doc.setTextColor(220, 220, 220);
    doc.setFontSize(40);
    doc.setFont('helvetica', 'bold');
    doc.text('CERTIFIED SAFE', 105, 130, { align: 'center', angle: 45 });

    // Footer
    doc.setTextColor(150, 150, 150);
    doc.setFontSize(8);
    doc.text(`Source Canteen: ${canteenName}`, 20, 275);
    doc.text(`A digital record of this certificate is stored in the Food Loop Blockchain.`, 20, 282);
    doc.text('© 2026 Food Loop Redistribution Network', 140, 282);

    doc.save(`Safety_Certificate_${certId}.pdf`);
    toast.success("Professional Safe Certificate generated!");
  } catch (err) {
    console.error(err);
    toast.error("Failed to generate certificate");
  }
};
